# Let NetworkManager manage all devices on this system
network:
  version: 2
  renderer: NetworkManager
  wifis:
    wlp4s0:
      dhcp4: no
      dhcp6: no
      addresses: [192.168.68.129/24]
      gateway4: 192.168.68.1
      nameservers:
        addresses: [127.0.0.1, 8.8.8.8, 9.9.9.9]
      access-points:
        "network_id":
           password: "****"
